# Generated by Django 4.1.5 on 2024-01-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twinTech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='job_poster/'),
        ),
    ]
